- name: Deploy a web application
  hosts: ubuntu_servers
  tasks:
    - name: Ping test
      ping: 

    - name: Install Python (setup tools, build essential, pip, git) required dependencies
      become: true
      # become_method: sudo
      apt:
        pkg:
          - python
          - python-setuptools
          - python-dev
          - build-essential
          - git
        state: present

    - name: Install MySQL required dependencies
      # become: true
      # become_method: sudo
      apt:
        pkg:
          - mysql-server
          - mysql-client
        state: present
    
    - name: Start MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes # on restart service will be started automatically.

    - name: Create Application Database
      mysql_db: name=employee_db state=present # present means???

    - name: Create Application Database user
      mysql_user:
        name: db_user
        password: a
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Install Python Flask dependencies
      pip: 
        name: "{{ item }}"
        state: present
      with_items:
        - flask
        - flask-mysql

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600